routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::resource('topic', 'TopicController');
    Route::resource('ticket', 'TicketController');
    Route::resource('ticket-comments', 'TicketCommentsController');
    Route::resource('report', 'ReportController');

    Route::get('ticket-cetak/{id}', 'TicketController@cetak')->name('cetak.ticket');
});

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

Route::get('/foo', function () {
    Artisan::call('storage:link');
});

resources/views/panels/breadcrumb.blade.php
<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <h2 class="content-header-title float-left mb-0">@yield('title')</h2>
                <div class="breadcrumb-wrapper col-12">
                    @if(@isset($breadcrumbs))
                        <ol class="breadcrumb">
                            {{-- this will load breadcrumbs dynamically from controller --}}
                            @foreach ($breadcrumbs as $breadcrumb)
                                <li class="breadcrumb-item">
                                    @if(isset($breadcrumb['link']))
                                        <a href="{{ $breadcrumb['link'] }}"> @endif{{$breadcrumb['name']}}@if(isset($breadcrumb['link'])) </a>
                                    @endif
                                </li>
                            @endforeach
                        </ol> 
                    @endisset
                </div>
            </div>
        </div>
    </div>
    <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
        <div class="form-group breadcrum-right">
            <div class="dropdown">
                <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="feather icon-settings"></i></button>
                <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Chat</a><a class="dropdown-item" href="#">Email</a><a class="dropdown-item" href="#">Calendar</a></div>
            </div>
        </div>
    </div>
</div>

resources/views/panels/footer.blade.php
<!-- BEGIN: Footer-->
@if($configData["mainLayoutType"] == 'horizontal' && isset($configData["mainLayoutType"]))
<footer
    class="footer {{ $configData['footerType'] }} {{($configData['footerType']=== 'footer-hidden') ? 'd-none':''}} footer-light navbar-shadow">
    @else
    <footer
        class="footer {{ $configData['footerType'] }} {{($configData['footerType']=== 'footer-hidden') ? 'd-none':''}} footer-light">
        @endif
        <p class="clearfix blue-grey lighten-2 mb-0"><span
                class="float-md-left d-block d-md-inline-block mt-25">Ticket Aja &copy; {{ date('Y') }}</span>
            <span
                class="float-md-right d-none d-md-block">Mercu Buana Jakarta</span>
            <button class="btn btn-primary btn-icon scroll-top" type="button"><i
                    class="feather icon-arrow-up"></i></button>
        </p>
    </footer>
    <!-- END: Footer-->

resources/views/panels/horizontalMenu.blade.php
@php
    $configData = Helper::applClasses();
@endphp
{{-- Horizontal Menu --}}
<div class="horizontal-menu-wrapper">
    <div class="header-navbar navbar-expand-sm navbar navbar-horizontal {{$configData['horizontalMenuClass']}} {{($configData['theme'] === 'light') ? "navbar-light" : "navbar-dark" }} navbar-without-dd-arrow navbar-shadow navbar-brand-center"
         role="navigation" data-menu="menu-wrapper" data-nav="brand-center">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mr-auto"><a class="navbar-brand" href="dashboard-analytics">
                        <div class="brand-logo"></div>
                        <h2 class="brand-text mb-0">Ticketing</h2>
                    </a></li>
                <li class="nav-item nav-toggle">
                    <a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse">
                        <i class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i>
                        <i class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary"
                           data-ticon="icon-disc"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Horizontal menu content-->
        <div class="navbar-container main-menu-content" data-menu="menu-container">
            <ul class="nav navbar-nav" id="main-menu-navigation" data-menu="menu-navigation">
                {{-- Foreach menu item starts --}}
                @if(isset($menuData[1]))
                    @foreach($menuData[1]->menu as $menu)
                        @php
                            $custom_classes = "";
                            if(isset($menu->classlist)) {
                            $custom_classes = $menu->classlist;
                            }
                            $translation = "";
                            if(isset($menu->i18n)){
                            $translation = $menu->i18n;
                            }

                            $explodeUrlRoute = explode('.', $menu->url);

                        @endphp
                        <li class="dropdown nav-item {{ $explodeUrlRoute[1] }} {{ (request()->routeIs($explodeUrlRoute[0] . '.' . $explodeUrlRoute[1] . '.*')  ) ? 'active' : '' }} {{ $custom_classes }}"
                            data-menu="dropdown">
                            <a href="{{ route($menu->url) }}" class="nav-link">
                                <i class="{{ $menu->icon }}"></i>
                                <span data-i18n="{{ $translation }}">{{ $menu->name }}</span>
                            </a>
                            @if(isset($menu->submenu))
                                @include('panels/horizontalSubmenu', ['menu' => $menu->submenu])
                            @endif
                        </li>
                    @endforeach
                @endif
                {{-- Foreach menu item ends --}}
            </ul>
        </div>
    </div>
</div>

resources/views/panels/horizontalSubmenu.blade.php
{{-- For Horizontal submenu --}}
<ul class="dropdown-menu">
    @if(isset($menu))
    @foreach($menu as $submenu)
    <?php
            $custom_classes = "";
            if(isset($submenu->classlist)) {
                $custom_classes = $submenu->classlist;
            }
            $submenuTranslation = "";
            if(isset($menu->i18n)){
                $submenuTranslation = $menu->i18n;
            }
        ?>
    <li
        class="{{ (request()->is($submenu->url)) ? 'active' : '' }} {{ (isset($submenu->submenu)) ? "dropdown dropdown-submenu" : '' }} {{ $custom_classes }}">
        <a href="{{ route($submenu->url) }}" class="dropdown-item {{ (isset($submenu->submenu)) ? "dropdown-toggle" : '' }}"
            {{ (isset($submenu->submenu)) ? 'data-toggle=dropdown' : '' }}>
            <i class="{{ isset($submenu->icon) ? $submenu->icon : "" }}"></i>
            <span data-i18n="{{ $submenuTranslation }}">{{ $submenu->name }}</span>
        </a>
        @if (isset($submenu->submenu))
        @include('panels/horizontalSubmenu', ['menu' => $submenu->submenu])
        @endif
    </li>
    @endforeach
    @endif
</ul>

resources/views/panels/navbar.blade.php
@if($configData["mainLayoutType"] == 'horizontal' && isset($configData["mainLayoutType"]))
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu {{ $configData['navbarColor'] }} navbar-fixed">
  <div class="navbar-header d-xl-block d-none">
    <ul class="nav navbar-nav flex-row">
      <li class="nav-item"><a class="navbar-brand" href="{{ route('home') }}">
          <div class="brand-logo"></div>
              <h2 class="brand-text mb-0">Ticketing <span class="d-block text-muted" style="font-size: 11px">Organizer Manager</span></h2>

          </a>
      </li>
    </ul>
  </div>
  @else
  <nav
    class="header-navbar navbar-expand-lg navbar navbar-with-menu {{ $configData['navbarClass'] }} navbar-light navbar-shadow {{ $configData['navbarColor'] }}">
    @endif
    <div class="navbar-wrapper">
      <div class="navbar-container content">
        <div class="navbar-collapse" id="navbar-mobile">
          <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
            <ul class="nav navbar-nav">
              <li class="nav-item mobile-menu d-xl-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs"
                  href="#"><i class="ficon feather icon-menu"></i></a></li>
            </ul>
          </div>
          <ul class="nav navbar-nav float-right">
              @guest
                  <li class="dropdown dropdown-user ">
                      <div class="p-1">
                          <a href="{{ route('login') }}" class="btn bg-gradient-primary waves-effect waves-light"><i class="feather icon-user"></i>Sign In</a>
                      </div>
                  </li>
              @else
                  <li class="dropdown dropdown-user nav-item">
                      <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                          <div class="user-nav d-sm-flex d-none">
                              <span class="user-name text-bold-600">{{ Auth::user()->name }}</span>
                              <span class="user-status">{{ Auth::user()->role->name }}</span>
                          </div>
                          <span>
                              @if (Auth::user()->avatar)
                                  <img class="round" src="{{ asset(Auth::user()->avatar) }}" alt="avatar" height="40" width="40" />
                              @else
                                  <img class="round" src="{{ asset('images/logo/avatar-no.png') }}" alt="avatar" height="40" width="40" />
                              @endif

                          </span>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right">
                          @can('isAdmin')
                          <a class="dropdown-item" href="{{ route('dashboard') }}"><i class="feather icon-home"></i> My Dashboard</a>
                          @endcan
                          <a class="dropdown-item" href="{{ config('app.env') === 'production' ? env('MAIN_DOMAIN') : env('MAIN_DOMAIN_DEV') }}" target="_blank"><i class="feather icon-navigation"></i> View Web</a>
                              <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i
                                  class="feather icon-power"></i> Logout</a>
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>
                      </div>
                  </li>
              @endguest
          </ul>
        </div>
      </div>
    </div>
  </nav>

resources/views/panels/scripts.blade.php
{{-- Vendor Scripts --}}
<script src="{{ asset(mix('vendors/js/vendors.min.js')) }}"></script>
<script src="{{ asset(mix('vendors/js/ui/prism.min.js')) }}"></script>
@yield('vendor-script')
{{-- Theme Scripts --}}
<script src="{{ asset(mix('js/core/app-menu.js')) }}"></script>
<script src="{{ asset(mix('js/core/app.js')) }}"></script>
<script src="{{ asset(mix('js/scripts/components.js')) }}"></script>
@if($configData['blankPage'] == false)
<script src="{{ asset(mix('js/scripts/customizer.js')) }}"></script>
<script src="{{ asset(mix('js/scripts/footer.js')) }}"></script>
@endif
{{-- page script --}}
@yield('page-script')
{{-- page script --}}

resources/views/panels/sidebar.blade.php
@php
$configData = Helper::applClasses();
@endphp
<div
  class="main-menu menu-fixed {{($configData['theme'] === 'light') ? "menu-light" : "menu-dark"}} menu-accordion menu-shadow"
  data-scroll-to-active="true">
  <div class="navbar-header">
    <ul class="nav navbar-nav flex-row">
      <li class="nav-item mr-auto">
        <a class="navbar-brand" href="{{ route('dashboard') }}">
          <div class="brand-logo"></div>
          <h2 class="brand-text mb-0">Ticket Aja</h2>
        </a>
      </li>
      <li class="nav-item nav-toggle">
        <a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse">
          <i class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i>
          <i class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block white collapse-toggle-icon"
            data-ticon="icon-disc">
          </i>
        </a>
      </li>
    </ul>
  </div>
  <div class="shadow-bottom"></div>
  <div class="main-menu-content">
    <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

        <li class="nav-item not-active">
            <a href="{{ route('dashboard') }}">
                <i class="feather icon-home"></i>
                <span class="menu-title" data-i18n="">Dashboard</span>
            </a>
        </li>

        @cannot('isTeknisi')
        <li class="nav-item not-active">
            <a href="{{ route('ticket.index') }}">
                <i class="feather icon-package"></i>
                <span class="menu-title" data-i18n="">Ticket</span>
            </a>
        </li>
        @endcannot

        @cannot('isCustomer')
        <li class="nav-item not-active">
            <a href="{{ route('report.index') }}">
                <i class="feather icon-bar-chart"></i>
                <span class="menu-title" data-i18n="">Laporan</span>
            </a>
        </li>
        @endcannot

        @canany(['isTeknisi', 'isCustomer'])
        @else
            <li class="navigation-header">
                <span>Master Data</span>
            </li>

            <li class="nav-item not-active">
                <a href="{{ route('topic.index') }}">
                    <i class="feather icon-layers"></i>
                    <span class="menu-title" data-i18n="">Topics</span>
                </a>
            </li>

            <li class="nav-item not-active">
                <a href="{{ route('users.index') }}">
                    <i class="feather icon-users"></i>
                    <span class="menu-title" data-i18n="">Users</span>
                </a>
            </li>

            <li class="nav-item not-active">
                <a href="{{ route('roles.index') }}">
                    <i class="feather icon-shield"></i>
                    <span class="menu-title" data-i18n="">Roles</span>
                    {{--                    <span class="badge badge-pill badge-primary float-right notTest">9+</span>--}}
                </a>
            </li>
        @endcanany

{{--        <li class="nav-item not-active">--}}
{{--            <a href="#">--}}
{{--                <i class="feather icon-external-link"></i>--}}
{{--                <span class="menu-title" data-i18n="">Dropdown</span>--}}
{{--            </a>--}}

{{--            <ul class="menu-content">--}}
{{--                <li class="not-active">--}}
{{--                    <a href="#">--}}
{{--                        <i class="feather icon-user"></i>--}}
{{--                        <span class="menu-title" data-i18n="">Submenu</span>--}}
{{--                    </a>--}}
{{--                </li>--}}
{{--            </ul>--}}
{{--        </li>--}}

    </ul>
  </div>
</div>
<!-- END: Main Menu-->

resources/views/panels/styles.blade.php
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,600,700">
<link rel="stylesheet" href="{{ asset(mix('vendors/css/vendors.min.css')) }}">
<link rel="stylesheet" href="{{ asset(mix('vendors/css/ui/prism.min.css')) }}">
{{-- Vendor Styles --}}
@yield('vendor-style')
{{-- Theme Styles --}}
<link rel="stylesheet" href="{{ asset(mix('css/bootstrap.css')) }}">
<link rel="stylesheet" href="{{ asset(mix('css/bootstrap-extended.css')) }}">
<link rel="stylesheet" href="{{ asset(mix('css/colors.css')) }}">
<link rel="stylesheet" href="{{ asset(mix('css/components.css')) }}">
<link rel="stylesheet" href="{{ asset(mix('css/themes/dark-layout.css')) }}">
<link rel="stylesheet" href="{{ asset(mix('css/themes/semi-dark-layout.css')) }}">
{{-- {!! Helper::applClasses() !!} --}}
@php
$configData = Helper::applClasses();
@endphp

{{-- Layout Styles works when don't use customizer --}}

{{-- @if($configData['theme'] == 'dark-layout')
        <link rel="stylesheet" href="{{ asset(mix('css/themes/dark-layout.css')) }}">
@endif
@if($configData['theme'] == 'semi-dark-layout')
<link rel="stylesheet" href="{{ asset(mix('css/themes/semi-dark-layout.css')) }}">
@endif --}}
{{-- Page Styles --}}
@if($configData['mainLayoutType'] === 'horizontal')
<link rel="stylesheet" href="{{ asset(mix('css/core/menu/menu-types/horizontal-menu.css')) }}">
@endif
<link rel="stylesheet" href="{{ asset(mix('css/core/menu/menu-types/vertical-menu.css')) }}">
<link rel="stylesheet" href="{{ asset(mix('css/core/colors/palette-gradient.css')) }}">
{{-- Page Styles --}}
@yield('page-style')
{{-- Laravel Style --}}
<link rel="stylesheet" href="{{ asset(mix('css/custom-laravel.css')) }}">
{{-- Custom RTL Styles --}}
@if($configData['direction'] === 'rtl' && isset($configData['direction']))
<link rel="stylesheet" href="{{ asset(mix('css/custom-rtl.css')) }}">
@endif

resources/views/panels/submenu.blade.php
{{-- For submenu --}}
<ul class="menu-content">
    @if(isset($menu))
    @foreach($menu as $submenu)
    <?php
            $submenuTranslation = "";
            if(isset($menu->i18n)){
                $submenuTranslation = $menu->i18n;
            }
        ?>
    <li class="{{ (request()->is($submenu->url)) ? 'active' : '' }}">
        <a href="{{ $submenu->url }}">
            <i class="{{ isset($submenu->icon) ? $submenu->icon : "" }}"></i>
            <span class="menu-title" data-i18n="{{ $submenuTranslation }}">{{ $submenu->name }}</span>
        </a>
        @if (isset($submenu->submenu))
        @include('panels/submenu', ['menu' => $submenu->submenu])
        @endif
    </li>
    @endforeach
    @endif
</ul>