routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::resource('topic', 'TopicController');
    Route::resource('ticket', 'TicketController');
    Route::resource('ticket-comments', 'TicketCommentsController');
    Route::resource('report', 'ReportController');

    Route::get('ticket-cetak/{id}', 'TicketController@cetak')->name('cetak.ticket');
});

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

Route::get('/foo', function () {
    Artisan::call('storage:link');
});

app/Models/Report.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    public function teknisi(){
        return $this->belongsTo(User::class, 'teknisi_id', 'id');
    }
}

app/Models/Ticket.php
<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function teknisi(){
        return $this->belongsTo(User::class, 'teknisi_id', 'id');
    }

    public function admin(){
        return $this->belongsTo(User::class, 'admin_id', 'id');
    }

    public function topic(){
        return $this->belongsTo(Topic::class);
    }

    public function comments(){
        return $this->hasMany(TicketComment::class);
    }

    public function reports(){
        return $this->hasMany(Report::class);
    }

    //mutator

    public function getStatusNameAttribute()
    {
        if ($this->status == 0){
            return "<span class='badge badge-pill badge-primary'>Open</span>";
        }elseif ($this->status == 1){
            return "<span class='badge badge-pill badge-warning'>On Progress</span>";
        }elseif ($this->status == 2){
            return "<span class='badge badge-pill badge-success'>Closed</span>";
        }elseif ($this->status == 3){
            return "<span class='badge badge-pill badge-danger'>Cancel</span>";
        }else{
            return "<span class='badge badge-pill badge-light'>Undefined</span>";
        }
    }

    public function getNoTicketAttribute()
    {
        $prefix = "TA";
        $dateString = Carbon::parse($this->created_at)->format('Ymd');
        $id = $this->id;
        return "#" . $prefix . $dateString . "-" .$id;
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Models\MasterRoles;
use App\Models\Report;
use App\Models\Ticket;
use App\Models\Topic;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id == 2 or Auth::user()->role_id == 4){
            if (isset($_GET['topic']) && $_GET['topic']){
                $datas = Ticket::where('teknisi_id', '!=', '')->where('topic_id', $_GET['topic'])->orderBy('created_at', 'DESC')->get();
            }else{
                $datas = Ticket::where('teknisi_id', '!=', '')->orderBy('created_at', 'DESC')->get();
            }
        }else{
            if (isset($_GET['topic']) && $_GET['topic']){
                $datas = Ticket::where('teknisi_id', Auth::user()->id)->where('topic_id', $_GET['topic'])->orderBy('created_at', 'DESC')->get();
            }else{
                $datas = Ticket::where('teknisi_id', Auth::user()->id)->orderBy('created_at', 'DESC')->get();
            }

        }

        $topics = Topic::all();

        return view('admin.report.report', compact('datas', 'topics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit = false;
        $topics = Topic::all();
        return view('admin.report.form', compact('edit', 'topics'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Report();
        $data->ticket_id = $request->ticket_id;
        $data->description= $request->comment;
        $data->teknisi_id = Auth::user()->id;

        if ($request->file('attachment')) {
            $file = $request->file('attachment')->store('attachment', 'public');
            $data->attachment = $file;
        }

        try{
            $data->save();
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Ticket::find($id);
        return view('admin.report.detail', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $data = Report::find($id);
        $topics = Topic::all();
        $teknisi = User::where('role_id', 3)->get();
        return view('admin.report.form', compact('edit','data', 'topics', 'teknisi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Report::find($id);
        $data->topic_id = $request->topic_id;
        $data->title = $request->title;
        $data->description = $request->description;
        $data->user_id = Auth::user()->id;
        $data->status = $request->status;
        $data->teknisi_id = $request->teknisi_id;

        if ($request->file('attachment')) {
            $file = $request->file('attachment')->store('attachment', 'public');
            $data->attachment = $file;
        }

        try{
            $data->save();
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('report.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            Report::destroy($id);
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('report.index');
    }
}

resources/views/admin/report/detail.blade.php
@extends('layouts.admin')

@section('title', 'Ticket Detail')

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <div class="card">
                    <div class="card-header mb-1">
                        <div class="card-title">
                            <h3>Ticket: {{ $data->title }}</h3>
                            <div>{!! $data->status_name  !!} {{ $data->noTicket }}</div>
                        </div>
                        <div>
                            <a href="{{ route('ticket.show', $data->id) }}">Lihat Detail</a>
                        </div>

                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Laporan</h4>
                    </div>
                    <div class="card-body">
                        @if(count($data->reports) > 0)
                            @foreach($data->reports as $report)
                                <div class="d-flex align-items-start mb-3">
                            <span class="mr-1">
                                @if ($report->teknisi->avatar)
                                    <img class="round" src="{{ asset('storage/' . $report->teknisi->avatar ) }}" alt="avatar" height="40" width="40">
                                @else
                                    <img class="round" src="{{ asset('images/logo/avatar-no.png') }}" alt="avatar" height="40" width="40" />
                                @endif

                            </span>
                                    <div class="mt-0 w-100">
                                        <div>{{ $report->teknisi->name }} <span class="badge badge-light">{{ $report->teknisi->role->name }}</span> <span class="float-right">{{ \Carbon\Carbon::parse($report->created_at)->diffForHumans() }}</span></div>
                                        <div class="p-2 mt-1 border border-accent-1 bg-white rounded">{{ $report->description }}</div>

                                        @if (($report ?? '') && (null != $report->attachment))
                                            <img src="{{ asset('storage/' . $report->attachment) }}" alt="" class="img-fluid rounded mt-2">
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        @else
                            <div class="alert alert-light">Tidak ada data</div>
                        @endif
                    </div>
                </div>

                    @if ($data->status == 0 or $data->status == 1)

                        @if(\Illuminate\Support\Facades\Auth::user()->id == $data->teknisi_id)

                    <div class="card">
                        <form action="{{route('report.store')}}" enctype="multipart/form-data" method="POST" class="form">
                        @csrf
                        <div class="card-header">
                            <h4 class="card-title">Buat Laporan</h4>
                            <button type="submit" class="btn btn-primary">Tambah</button>
                        </div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <input type="hidden" name="ticket_id" value="{{ $data->id }}">
                            <textarea class="form-control w-100" name="comment" required placeholder="Write here..."></textarea>
                                <div class="custom-file mt-2">
                                    <input type="file" class="custom-file-input" id="inputGroupFile01" name="attachment" value="{{ old('attachment') }}">
                                    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                </div>
                        </div>
                        </form>
                    </div>
                        @endif

                    @endif
            </div>
        </div>
    </div>
@endsection

@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
@endsection
@section('page-script')
    {{-- Page js files --}}
    <script src="{{ asset(mix('js/scripts/datatables/datatable.js')) }}"></script>
@endsection

resources/views/admin/report/form.blade.php
@extends('layouts/admin')

@section('title', 'Topic Detail')
@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/pickers/pickadate/pickadate.css')) }}">


    <link rel="stylesheet" href="{{ asset(mix('vendors/css/editors/quill/quill.snow.css')) }}">
@endsection
@section('content')

    <section id="basic-horizontal-layouts">
        <div class="row match-height d-flex justify-content-center">
            <div class="col-md-6 col-12">
                @if(session('status'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{session('status')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                @if ($edit)
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('ticket.update', $data->id)}}" method="post">
                            @method('PUT')
                @else
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('ticket.store')}}" method="post">
                @endif
                    @csrf
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ $edit ? 'Edit ticket' : 'Tambah ticket' }}</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-12">
                                                    <span>Topic</span>
                                                </div>
                                                <div class="col-md-12">
                                                    <select name="topic_id" class="form-control" id="topic_id">
                                                        @foreach($topics as $value)
                                                            <option value="{{ $value->id }}" {{ ($edit && $value->id == $data->topic_id) ? 'selected' : '' }}>{{ $value->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-12">
                                                    <span>Subject</span>
                                                </div>
                                                <div class="col-md-12">
                                                    <input type="text" id="title" name="title" class="form-control" value="{{ $edit ? $data->title : old('title') }}" required>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-12">
                                                    <span>Message</span>
                                                </div>
                                                <div class="col-md-12">
                                                    <div id="snow-container">
                                                        <div class="editor">
                                                            {!! $edit ?? '' ? $data->description : old('description')  !!}
                                                        </div>
                                                        <textarea name="description" id="description" class="d-none">
                                                            {{ $edit ?? '' ? $data->description : old('description') }}
                                                        </textarea>
                                                    </div>
                                                    <div class="caption text-danger mt-1">{{ $errors->first('description') }}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-12">
                                                    <span>Attachment</span>
                                                </div>
                                                <div class="col-md-12">
                                                    @if (($data ?? '') && (null != $data->attachment))
                                                        <img src="{{ asset('storage/' . $data->attachment) }}" alt="" class="img-fluid rounded mb-3">
                                                    @endif
                                                    <div class="custom-file">
                                                        <input type="file" class="custom-file-input" id="inputGroupFile01" name="attachment" value="{{ old('attachment') }}">
                                                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    @if($edit)
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-12">
                                                    <span>Status</span>
                                                </div>
                                                <div class="col-md-12">
                                                    <select name="status" class="form-control" id="status">
                                                        <option value="0" {{ ($edit && 0 == $data->status) ? 'selected' : '' }}>Open</option>
                                                        <option value="1" {{ ($edit && 1 == $data->status) ? 'selected' : '' }}>On Progress</option>
                                                        <option value="2" {{ ($edit && 2 == $data->status) ? 'selected' : '' }}>Closed</option>
                                                        <option value="3" {{ ($edit && 3 == $data->status) ? 'selected' : '' }}>Cancel</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group row">
                                                    <div class="col-md-12">
                                                        <span>Tugaskan Teknisi</span>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <select name="teknisi_id" class="form-control" id="teknisi_id">
                                                            <option value="">-- Piih Teknisi --</option>
                                                            @foreach($teknisi as $value)
                                                                <option value="{{ $value->id }}" {{ ($edit && $value->id == $data->teknisi_id) ? 'selected' : '' }}>{{ $value->name }}</option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endif
                                </div>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        <span class="float-left">
                            <button type="reset" class="btn btn-outline-warning">Reset</button>
                        </span>
                        <span class="float-right">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </span>
                    </div>
                </div>
                </form>
            </div>
    </section>

@endsection

@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.date.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.time.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/legacy.js')) }}"></script>

    <script src="{{ asset(mix('vendors/js/editors/quill/katex.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/highlight.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/quill.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/extensions/jquery.steps.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
@endsection
@section('page-script')
    <!-- Page js files -->
    <script src="{{ asset(mix('js/scripts/forms/select/form-select2.js')) }}"></script>
    <script src="{{ asset(mix('js/scripts/pickers/dateTime/pick-a-datetime.js')) }}"></script>



    <script>
        var editor = new Quill('#snow-container .editor', {
            bounds: '#snow-container .editor',
            modules: {

                toolbar: [
                    ['bold', 'italic', 'underline'],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    ['clean']
                ]
            },
            theme: 'snow'
        });

        var justHtmlContent = document.getElementById('description');

        editor.on('text-change', function() {
            var justHtml = editor.root.innerHTML;
            justHtmlContent.innerHTML = justHtml;
        });
    </script>
@endsection

resources/views/admin/report/report.blade.php
@extends('layouts.admin')

@section('title', 'Report')

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header mb-1">
                        <h4 class="card-title">List Report</h4>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                            <div class="row">
                                <div class="col-md-3 mb-2">
                                    <select id="filterTopic" class="form-control">
                                        <option value="0">Pilih Topik</option>
                                        @foreach($topics as $val)
                                            <option value="{{ $val->id }}" {{ isset($_GET['topic']) && ($_GET['topic'] == $val->id) ? 'selected' : '' }}>{{ $val->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="table-responsive">
                                <table class="table table-striped zero-configuration">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Status</th>
                                        <th>Tiket</th>
                                        <th>Topic</th>
                                        <th>Teknisi</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($datas as $val)

                                        <tr>
                                            <td>{{ $val->id }}</td>
                                            <td>{!!$val->StatusName !!}</td>
                                            <td>{{ $val->title }}</td>
                                            <td>{{ $val->topic->name }}</td>
                                            <td>{{ $val->teknisi->name }}</td>
                                            <td>
                                                <a href="{{ route('report.show', $val->id) }}" class="btn btn-primary btn-sm">Detail</a>
                                            </td>
                                        </tr>

                                    @endforeach

                                    </tbody>

                                </table>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
@endsection
@section('page-script')
    {{-- Page js files --}}
    <script src="{{ asset(mix('js/scripts/datatables/datatable.js')) }}"></script>

    <script>
        $('#filterTopic').on('change', function (){
            var valueTopic = $('#filterTopic').val();
            if (valueTopic == 0){
                window.location.href='report'
            }else{
                window.location.href='?topic=' + valueTopic
            }
        });
    </script>
@endsection